services:
  - type: web
    name: MF0493
    env: docker
    plan: free
    repo: https://github.com/JssDevWeb/MF0493.git
    branch: master
    rootDir: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        # Si no la pones, Render asignará una por defecto. Puedes añadirla después del primer despliegue.
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0lmjmqdbo4c73aq2k5g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: ejercicio1_fxem
      - key: DB_USERNAME
        value: ejercicio1_fxem_user
      - key: DB_PASSWORD
        value: 8za6aHBE3sdDhO96ogANP43JNYzuSwCj
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync